name = "keystone-aiml"
main = "dist/worker.js"
compatibility_date = "2025-12-17"

# Remove this if you are not using KV
# kv_namespaces = [{ binding = "__STATIC_CONTENT" }]

[[d1_databases]]
binding = "KESTONE_D1"
database_name = "keystone_db"
database_id = "e1741c9b-c08d-44d4-a60d-49d965e82cdd"

